//! TypeScript export.
//!
//! `ARCHITECTURE_SPEC.md` §6: types are defined once in Rust and generated into
//! TypeScript. There is no hand-maintained duplicate, so the UI cannot drift
//! from the daemon without the build noticing.
//!
//! [`export_bindings`] is deliberately a normal function rather than a set of
//! `#[ts(export)]` attributes. It gives one place that knows the export roots,
//! writes a barrel `index.ts`, and can be called from a build task later without
//! going through the test harness.

use std::path::Path;
use std::{fs, io};

use ts_rs::{Config, ExportError, TS};

use crate::{
    Command, Cue, Delta, Executor, Fixture, FixtureType, Group, JsonValue, OutputHealth, Preset,
    ProgrammerState, Sequence, Session, View,
};

/// Where the bindings live, relative to the workspace root.
pub const BINDINGS_DIR: &str = "ui/src/bindings";

/// Header written to the generated barrel file.
const INDEX_HEADER: &str = "\
// Generated by prism-domain (cargo test -p prism-domain). Do not edit.
// Source of truth: crates/prism-domain/src, ARCHITECTURE_SPEC.md §6,
// docs/IPC_PROTOCOL.md §5-6.
";

/// Writes the TypeScript bindings for every domain type into `out_dir`.
///
/// The directory is emptied first, so a type that has been removed in Rust
/// cannot leave a stale binding behind. Returns the exported type names, sorted.
///
/// # Errors
///
/// Fails if the directory cannot be replaced or a binding cannot be written.
pub fn export_bindings(out_dir: &Path) -> Result<Vec<String>, ExportError> {
    replace_dir(out_dir).map_err(ExportError::Io)?;

    // `export_all` pulls in every dependency, so only the roots are listed:
    // the two wire enums, and the show and session types they do not reach.
    let cfg = Config::new().with_out_dir(out_dir).with_large_int("number");
    Command::export_all(&cfg)?;
    Delta::export_all(&cfg)?;
    FixtureType::export_all(&cfg)?;
    Fixture::export_all(&cfg)?;
    Group::export_all(&cfg)?;
    Preset::export_all(&cfg)?;
    Cue::export_all(&cfg)?;
    Sequence::export_all(&cfg)?;
    Executor::export_all(&cfg)?;
    ProgrammerState::export_all(&cfg)?;
    Session::export_all(&cfg)?;
    View::export_all(&cfg)?;
    OutputHealth::export_all(&cfg)?;
    JsonValue::export_all(&cfg)?;

    let names = exported_names(out_dir).map_err(ExportError::Io)?;
    write_index(out_dir, &names).map_err(ExportError::Io)?;
    Ok(names)
}

/// Removes `dir` and recreates it empty.
fn replace_dir(dir: &Path) -> io::Result<()> {
    match fs::remove_dir_all(dir) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }
    fs::create_dir_all(dir)
}

/// The stem of every `.ts` file in `dir` except the barrel, sorted.
fn exported_names(dir: &Path) -> io::Result<Vec<String>> {
    let mut names = Vec::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "ts")
            && let Some(stem) = path.file_stem().and_then(|stem| stem.to_str())
            && stem != "index"
        {
            names.push(stem.to_owned());
        }
    }
    names.sort();
    Ok(names)
}

/// Writes the barrel file that re-exports every binding.
fn write_index(dir: &Path, names: &[String]) -> io::Result<()> {
    let mut contents = String::from(INDEX_HEADER);
    contents.push('\n');
    for name in names {
        contents.push_str(&format!("export type {{ {name} }} from \"./{name}\";\n"));
    }
    fs::write(dir.join("index.ts"), contents)
}

/// Absolute path of [`BINDINGS_DIR`], derived from this crate's location.
#[cfg(test)]
pub(crate) fn bindings_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(BINDINGS_DIR)
}

/// Exports the bindings exactly once per test binary and returns the type names.
///
/// Several tests need the generated output, and they run on different threads;
/// exporting more than once would mean one test deleting the directory another
/// is reading.
#[cfg(test)]
pub(crate) fn exported_once() -> &'static [String] {
    static NAMES: std::sync::OnceLock<Vec<String>> = std::sync::OnceLock::new();
    NAMES.get_or_init(|| export_bindings(&bindings_dir()).expect("bindings must export"))
}

#[cfg(test)]
mod tests {
    use super::{bindings_dir, exported_once};
    use std::fs;

    /// Regenerating on every test run is what keeps the bindings honest: a type
    /// changed in Rust and not regenerated cannot survive a green build.
    #[test]
    fn writes_bindings_for_every_domain_type() {
        let dir = bindings_dir();
        let names = exported_once();

        assert!(names.contains(&"Command".to_owned()));
        assert!(names.contains(&"Delta".to_owned()));
        assert!(names.contains(&"FixtureId".to_owned()));
        assert!(names.contains(&"Session".to_owned()));
        assert!(names.len() > 30, "only {} types exported", names.len());

        let index = fs::read_to_string(dir.join("index.ts")).unwrap();
        for name in names {
            assert!(
                index.contains(&format!("export type {{ {name} }} from \"./{name}\";")),
                "index.ts is missing {name}"
            );
        }
    }

    /// `CLAUDE.md` forbids `any`. `serde_json::Value` would have produced one,
    /// which is why `JsonValue` exists.
    #[test]
    fn no_generated_binding_contains_any() {
        let dir = bindings_dir();
        exported_once();

        for entry in fs::read_dir(&dir).unwrap() {
            let path = entry.unwrap().path();
            let contents = fs::read_to_string(&path).unwrap();
            for (number, line) in contents.lines().enumerate() {
                assert!(
                    !contains_any_type(line),
                    "{}:{} uses `any`: {line}",
                    path.display(),
                    number + 1
                );
            }
        }
    }

    #[test]
    fn the_any_detector_distinguishes_the_type_from_the_word() {
        assert!(contains_any_type("export type X = any;"));
        assert!(contains_any_type("values: Array<any>,"));
        assert!(contains_any_type("params: { [key in string]: any },"));

        assert!(!contains_any_type(" * applied after any attribute invert"));
        assert!(!contains_any_type("// any of these"));
        assert!(!contains_any_type("/** any prose */"));
        assert!(!contains_any_type("company: string,"));
        assert!(!contains_any_type("anything: string,"));
    }

    /// `any` as a TypeScript type, not as part of a longer word or a comment.
    ///
    /// Doc comments are carried over from the Rust doc comments verbatim, so
    /// prose like "after any attribute-level invert" appears in the output and
    /// must not be mistaken for a type.
    fn contains_any_type(line: &str) -> bool {
        let trimmed = line.trim_start();
        if trimmed.starts_with("//") || trimmed.starts_with('*') || trimmed.starts_with("/*") {
            return false;
        }
        let line = trimmed;
        line.match_indices("any").any(|(index, _)| {
            let before = line[..index].chars().next_back();
            let after = line[index + 3..].chars().next();
            let is_word_char = |c: char| c.is_alphanumeric() || c == '_' || c == '$';
            !before.is_some_and(is_word_char) && !after.is_some_and(is_word_char)
        })
    }
}
