//! TypeScript export.
//!
//! `ARCHITECTURE_SPEC.md` §6: types are defined once in Rust and generated into
//! TypeScript. There is no hand-maintained duplicate, so the UI cannot drift
//! from the daemon without the build noticing.
//!
//! [`export_bindings`] is deliberately a normal function rather than a set of
//! `#[ts(export)]` attributes. It gives one place that knows the export roots,
//! writes a barrel `index.ts`, and can be called from a build task later without
//! going through the test harness.
//!
//! # A type is compile-time only, and a decoder needs values (S23)
//!
//! `ts-rs` renders a unit-only enum as a union of string literals, which is
//! exactly right for a type and useless to code that has to decide whether the
//! string it just decoded off a socket *is* one. The UI decodes a message into
//! `unknown` and narrows it with type guards — `CLAUDE.md` forbids `any`, and
//! `as` is not a check — so it needs the list at run time.
//!
//! [`write_variants`] therefore emits `variants.ts` beside the types, and it
//! derives each list **from the generated union itself** rather than from a
//! second enumeration in Rust. Two sources for one list is the drift this whole
//! module exists to prevent, so there is only ever one: what `ts-rs` wrote.

use std::path::Path;
use std::{fs, io};

use ts_rs::{Config, ExportError, TS};

use crate::{
    Command, Cue, Delta, Executor, Fixture, FixtureType, Group, JsonValue, OutputHealth, Preset,
    ProgrammerState, Sequence, Session, View,
};

/// Where the bindings live, relative to the workspace root.
pub const BINDINGS_DIR: &str = "ui/src/bindings";

/// Header written to the generated barrel file.
const INDEX_HEADER: &str = "\
// Generated by prism-domain (cargo test -p prism-domain). Do not edit.
// Source of truth: crates/prism-domain/src, ARCHITECTURE_SPEC.md §6,
// docs/IPC_PROTOCOL.md §5-6.
";

/// Header written to the generated variant tables.
const VARIANTS_HEADER: &str = "\
// Generated by prism-domain (cargo test -p prism-domain). Do not edit.
//
// The run-time tables for the string unions in this directory. A TypeScript
// type is erased at run time, and a client that decodes a message into
// `unknown` has to *check* that the string it was given is one of these -
// `as` is a claim, not a check, and `CLAUDE.md` forbids `any`.
//
// Every list here is read back out of the union `ts-rs` generated, so the
// values and the type cannot disagree.
";

/// Name of the generated variant tables, without the extension.
const VARIANTS: &str = "variants";

/// Writes the TypeScript bindings for every domain type into `out_dir`.
///
/// Existing `.ts` files in that directory are removed first, so a type that has
/// been removed in Rust cannot leave a stale binding behind. Nothing else is
/// touched and no directory is deleted — a mistyped path costs at most the
/// generated files it was pointed at. Returns the exported type names, sorted.
///
/// # Errors
///
/// Fails if the directory cannot be prepared or a binding cannot be written.
pub fn export_bindings(out_dir: &Path) -> Result<Vec<String>, ExportError> {
    clear_generated(out_dir).map_err(ExportError::Io)?;

    // `export_all` pulls in every dependency, so only the roots are listed:
    // the two wire enums, and the show and session types they do not reach.
    let cfg = Config::new().with_out_dir(out_dir).with_large_int("number");
    Command::export_all(&cfg)?;
    Delta::export_all(&cfg)?;
    FixtureType::export_all(&cfg)?;
    Fixture::export_all(&cfg)?;
    Group::export_all(&cfg)?;
    Preset::export_all(&cfg)?;
    Cue::export_all(&cfg)?;
    Sequence::export_all(&cfg)?;
    Executor::export_all(&cfg)?;
    ProgrammerState::export_all(&cfg)?;
    Session::export_all(&cfg)?;
    View::export_all(&cfg)?;
    OutputHealth::export_all(&cfg)?;
    JsonValue::export_all(&cfg)?;

    let names = exported_names(out_dir).map_err(ExportError::Io)?;
    write_variants(out_dir, &names).map_err(ExportError::Io)?;
    write_index(out_dir, &names).map_err(ExportError::Io)?;
    Ok(names)
}

/// Creates `dir` if needed and deletes the `.ts` files already in it.
fn clear_generated(dir: &Path) -> io::Result<()> {
    fs::create_dir_all(dir)?;
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_file() && path.extension().is_some_and(|extension| extension == "ts") {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

/// The stem of every `.ts` file in `dir` except the two generated files that
/// are about the bindings rather than one of them, sorted.
fn exported_names(dir: &Path) -> io::Result<Vec<String>> {
    let mut names = Vec::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "ts")
            && let Some(stem) = path.file_stem().and_then(|stem| stem.to_str())
            && stem != "index"
            && stem != VARIANTS
        {
            names.push(stem.to_owned());
        }
    }
    names.sort();
    Ok(names)
}

/// Writes the barrel file that re-exports every binding.
fn write_index(dir: &Path, names: &[String]) -> io::Result<()> {
    let mut contents = String::from(INDEX_HEADER);
    contents.push('\n');
    for name in names {
        contents.push_str(&format!("export type {{ {name} }} from \"./{name}\";\n"));
    }
    // The one line that exports values rather than types: `variants.ts` is a
    // table, and a table erased at compile time would be no use to a decoder.
    contents.push_str(&format!("\nexport * from \"./{VARIANTS}\";\n"));
    fs::write(dir.join("index.ts"), contents)
}

/// Writes the run-time tables for every binding that is a union of string
/// literals, and returns the type names it wrote a table for.
///
/// See the module documentation: the values are read back out of the generated
/// unions, so there is one list rather than two that can disagree.
fn write_variants(dir: &Path, names: &[String]) -> io::Result<Vec<String>> {
    let mut tables = Vec::new();
    for name in names {
        if let Some(values) =
            string_union(&fs::read_to_string(dir.join(format!("{name}.ts")))?, name)
        {
            tables.push((name.clone(), values));
        }
    }

    let mut contents = String::from(VARIANTS_HEADER);
    contents.push('\n');
    for (name, _) in &tables {
        contents.push_str(&format!("import type {{ {name} }} from \"./{name}\";\n"));
    }
    for (name, values) in &tables {
        let literals = values
            .iter()
            .map(|value| format!("\"{value}\""))
            .collect::<Vec<_>>()
            .join(", ");
        contents.push_str(&format!(
            "\n/** Every {name}, in the order `prism-domain` declares them. */\nexport const {}_VARIANTS: readonly {name}[] = [{literals}];\n",
            screaming_snake(name)
        ));
    }
    fs::write(dir.join(format!("{VARIANTS}.ts")), contents)?;
    Ok(tables.into_iter().map(|(name, _)| name).collect())
}

/// The string literals of `export type <name> = "a" | "b";`, or `None` if the
/// binding is anything else.
///
/// Deliberately strict: one literal that is not a plain quoted string — an
/// object member, a `number`, an escape — makes the whole type ineligible
/// rather than half-listed. `JsonValue`, whose union ends in an index
/// signature, is the case that has to come back `None`.
fn string_union(source: &str, name: &str) -> Option<Vec<String>> {
    let head = format!("export type {name} = ");
    let start = source.find(&head)? + head.len();
    let body = &source[start..];
    let body = &body[..body.find(';')?];

    let mut values = Vec::new();
    for part in body.split('|') {
        let literal = part.trim().strip_prefix('"')?.strip_suffix('"')?;
        if literal.contains(['"', '\\']) || literal.is_empty() {
            return None;
        }
        values.push(literal.to_owned());
    }
    (!values.is_empty()).then_some(values)
}

/// `AttributeType` as `ATTRIBUTE_TYPE`.
fn screaming_snake(name: &str) -> String {
    let characters: Vec<char> = name.chars().collect();
    let mut out = String::with_capacity(name.len() + 4);
    for (index, character) in characters.iter().enumerate() {
        let previous = index
            .checked_sub(1)
            .and_then(|before| characters.get(before));
        let next = characters.get(index + 1);
        let boundary = character.is_ascii_uppercase()
            && previous.is_some_and(|before| {
                before.is_lowercase()
                    || before.is_ascii_digit()
                    || (before.is_ascii_uppercase() && next.is_some_and(char::is_ascii_lowercase))
            });
        if boundary {
            out.push('_');
        }
        out.push(character.to_ascii_uppercase());
    }
    out
}

/// Absolute path of [`BINDINGS_DIR`], derived from this crate's location.
#[cfg(test)]
pub(crate) fn bindings_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(BINDINGS_DIR)
}

/// Exports the bindings exactly once per test binary and returns the type names.
///
/// Several tests need the generated output, and they run on different threads;
/// exporting more than once would mean one test deleting the directory another
/// is reading.
#[cfg(test)]
pub(crate) fn exported_once() -> &'static [String] {
    static NAMES: std::sync::OnceLock<Vec<String>> = std::sync::OnceLock::new();
    NAMES.get_or_init(|| export_bindings(&bindings_dir()).expect("bindings must export"))
}

#[cfg(test)]
mod tests {
    use super::{bindings_dir, exported_once, screaming_snake, string_union};
    use std::fs;

    /// Regenerating on every test run is what keeps the bindings honest: a type
    /// changed in Rust and not regenerated cannot survive a green build.
    #[test]
    fn writes_bindings_for_every_domain_type() {
        let dir = bindings_dir();
        let names = exported_once();

        assert!(names.contains(&"Command".to_owned()));
        assert!(names.contains(&"Delta".to_owned()));
        assert!(names.contains(&"FixtureId".to_owned()));
        assert!(names.contains(&"Session".to_owned()));
        assert!(names.len() > 30, "only {} types exported", names.len());

        let index = fs::read_to_string(dir.join("index.ts")).unwrap();
        for name in names {
            assert!(
                index.contains(&format!("export type {{ {name} }} from \"./{name}\";")),
                "index.ts is missing {name}"
            );
        }
        assert!(
            index.contains("export * from \"./variants\";"),
            "the barrel has to carry the one file that exports values"
        );
    }

    /// The tables the UI narrows a decoded string with (S23), against the
    /// enums themselves rather than against the file that was just written.
    ///
    /// `serde_json` is what puts the *wire* spelling in the assertion:
    /// `MergeMode` renames its variants to upper case, and a table listing
    /// `Htp` would type-check in TypeScript and never match a message.
    #[test]
    fn the_variant_tables_hold_every_variant_in_its_wire_spelling() {
        exported_once();
        let variants = fs::read_to_string(bindings_dir().join("variants.ts")).unwrap();

        let spellings = |values: &[String]| values.join(", ");
        let expected = [
            (
                "ATTRIBUTE_TYPE_VARIANTS",
                crate::AttributeType::ALL
                    .iter()
                    .map(|value| serde_json::to_string(value).unwrap())
                    .collect::<Vec<_>>(),
            ),
            (
                "FEATURE_GROUP_VARIANTS",
                crate::FeatureGroup::ALL
                    .iter()
                    .map(|value| serde_json::to_string(value).unwrap())
                    .collect::<Vec<_>>(),
            ),
        ];
        for (table, values) in expected {
            let literals = spellings(&values);
            assert!(
                variants.contains(&format!("export const {table}: readonly ")),
                "variants.ts has no {table}"
            );
            assert!(
                variants.contains(&format!("= [{literals}];")),
                "{table} is not {literals}"
            );
        }

        // The renamed one, written out by hand: a table generated from the type
        // and a type generated from the enum would both be wrong together if
        // `rename_all` were ever dropped.
        assert!(
            variants.contains(
                "export const MERGE_MODE_VARIANTS: readonly MergeMode[] = [\"HTP\", \"LTP\"];"
            ),
            "{variants}"
        );
        // And the wire enums, which are unions of *objects*, get no table at
        // all — a partial list would be worse than none.
        assert!(!variants.contains("COMMAND_VARIANTS"));
        assert!(!variants.contains("DELTA_VARIANTS"));
        assert!(!variants.contains("JSON_VALUE_VARIANTS"));
    }

    #[test]
    fn only_a_union_of_plain_string_literals_becomes_a_table() {
        assert_eq!(
            string_union("export type X = \"a\" | \"b\";", "X"),
            Some(vec!["a".to_owned(), "b".to_owned()])
        );
        assert_eq!(
            string_union("export type X = \"only\";", "X"),
            Some(vec!["only".to_owned()])
        );
        // A number, an object member, an index signature, an escaped quote, an
        // empty literal, and a type that is not there at all.
        assert_eq!(string_union("export type X = number;", "X"), None);
        assert_eq!(string_union("export type X = \"a\" | { b: 1 };", "X"), None);
        assert_eq!(
            string_union("export type X = \"a\" | { [key in string]: X };", "X"),
            None
        );
        assert_eq!(string_union("export type X = \"a\\\"b\";", "X"), None);
        assert_eq!(string_union("export type X = \"\";", "X"), None);
        assert_eq!(string_union("export type Y = \"a\";", "X"), None);
        assert_eq!(string_union("export type X = \"a\"", "X"), None);
    }

    #[test]
    fn a_type_name_becomes_a_constant_name() {
        assert_eq!(screaming_snake("AttributeType"), "ATTRIBUTE_TYPE");
        assert_eq!(screaming_snake("OutputHealth"), "OUTPUT_HEALTH");
        assert_eq!(
            screaming_snake("ProgrammerValueSource"),
            "PROGRAMMER_VALUE_SOURCE"
        );
        assert_eq!(screaming_snake("RgbColor"), "RGB_COLOR");
        assert_eq!(screaming_snake("Viewer3D"), "VIEWER3_D");
    }

    /// `CLAUDE.md` forbids `any`. `serde_json::Value` would have produced one,
    /// which is why `JsonValue` exists.
    #[test]
    fn no_generated_binding_contains_any() {
        let dir = bindings_dir();
        exported_once();

        for entry in fs::read_dir(&dir).unwrap() {
            let path = entry.unwrap().path();
            let contents = fs::read_to_string(&path).unwrap();
            for (number, line) in contents.lines().enumerate() {
                assert!(
                    !contains_any_type(line),
                    "{}:{} uses `any`: {line}",
                    path.display(),
                    number + 1
                );
            }
        }
    }

    #[test]
    fn the_any_detector_distinguishes_the_type_from_the_word() {
        assert!(contains_any_type("export type X = any;"));
        assert!(contains_any_type("values: Array<any>,"));
        assert!(contains_any_type("params: { [key in string]: any },"));

        assert!(!contains_any_type(" * applied after any attribute invert"));
        assert!(!contains_any_type("// any of these"));
        assert!(!contains_any_type("/** any prose */"));
        assert!(!contains_any_type("company: string,"));
        assert!(!contains_any_type("anything: string,"));
    }

    /// `any` as a TypeScript type, not as part of a longer word or a comment.
    ///
    /// Doc comments are carried over from the Rust doc comments verbatim, so
    /// prose like "after any attribute-level invert" appears in the output and
    /// must not be mistaken for a type.
    fn contains_any_type(line: &str) -> bool {
        let trimmed = line.trim_start();
        if trimmed.starts_with("//") || trimmed.starts_with('*') || trimmed.starts_with("/*") {
            return false;
        }
        let line = trimmed;
        line.match_indices("any").any(|(index, _)| {
            let before = line[..index].chars().next_back();
            let after = line[index + 3..].chars().next();
            let is_word_char = |c: char| c.is_alphanumeric() || c == '_' || c == '$';
            !before.is_some_and(is_word_char) && !after.is_some_and(is_word_char)
        })
    }
}
