//! What *this machine* is set to, as opposed to what it is playing — S37.
//!
//! # Why these are settings and not flags
//!
//! Until S37 everything in this module was a `prismd` command-line argument.
//! That is the right shape for a bring-up and the wrong shape for a venue: a
//! school's caretaker does not edit a shortcut's arguments, and a setting that
//! only exists on a command line is one nobody can read back. S33 made the
//! **rig** data and S36 made the **surface** data, both for that reason and both
//! landing in `prism_core::MachineConfig`; this is the rest of the list, and it
//! lands in the same place.
//!
//! Three families:
//!
//! - **Network exposure** — whether the local pipe is open, whether the
//!   WebSocket listener is open and where, and the §2.1 token. `docs/IPC_PROTOCOL.md`
//!   §2.1 is the rule the daemon enforces: *a listener off loopback needs a
//!   token*, and the token is generated by the daemon and displayed by the
//!   interface rather than invented by a client.
//! - **What the daemon is** — the log level, how many universes the frame layout
//!   carries, what the stage does when it stops, whether it starts with the
//!   machine (S29), where the fixture library was installed and which surface
//!   binding profile is in force.
//! - **This desk's identity** — read, and made anew when two machines have come
//!   to share one. That is not hypothetical: a school images one laptop onto
//!   twenty, and `prism_core::desk` explains what two sACN sources under one CID
//!   look like to a receiver.
//!
//! # A command line still wins, and the interface has to say so
//!
//! A flag that names one of these is *the value for that run*, exactly as S33's
//! output flags and S36's `--surface` are: the stored setting is neither read
//! nor written. So [`MachineSettings::overrides`] carries which of them the
//! command line is holding, because a box an operator can type into that does
//! nothing is worse than a box that is not there.
//!
//! # What takes effect now and what takes effect next time
//!
//! [`MachineChange::needs_restart`] answers it, and it is the domain's answer
//! rather than a list in an interface — the same decision
//! [`crate::OutputInstance::needs_restart`] records for a rig. A listener is
//! bound once, a frame layout is built once, and **a new desk identity is
//! deliberately in that group**: changing the CID of a live sACN source is the
//! two-and-a-half-second fight between an old source and a new one that
//! `prism_core::desk` describes, so the right moment for it is a start rather
//! than a show.

use std::net::SocketAddr;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// How much the daemon writes to its log.
///
/// The domain's copy of `prismd::log::Level`, and the two are deliberately
/// separate types: the daemon's is what a logger switches on, this is what
/// travels and what a settings window draws. `prismd` converts between them in
/// one place.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Serialize, Deserialize, TS,
)]
#[cfg_attr(any(test, feature = "proptest"), derive(proptest_derive::Arbitrary))]
pub enum LogLevel {
    /// Everything, including the per-poll detail.
    Debug,
    /// What a running desk does. The default.
    #[default]
    Info,
    /// Only what somebody should look at.
    Warn,
    /// Only what has gone wrong.
    Error,
    /// Nothing at all.
    Off,
}

/// What the stage does when the daemon is stopped on purpose.
///
/// `ARCHITECTURE_SPEC.md` §10.3, and the default is [`Self::Hold`] for S10's
/// reason: *the desk is stopping* and *the stage should go dark* are different
/// statements, and only one of them was made.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Serialize, Deserialize, TS,
)]
#[cfg_attr(any(test, feature = "proptest"), derive(proptest_derive::Arbitrary))]
pub enum ExitAction {
    /// Leave the last look where it is.
    #[default]
    Hold,
    /// Publish a blackout, give the outputs time to send it, then stop.
    Blackout,
}

/// One setting of this machine, changed on its own — `Command::ConfigureMachine`.
///
/// **One field per command**, which is [`crate::OutputChange`]'s rule and
/// `CueProperty`'s before it: a command carrying the whole of
/// [`MachineSettings`] would make a client read it, change one member and send
/// the rest back, and two operators in two settings windows would each undo the
/// other.
///
/// Two of the variants carry no value because the value is the *daemon's* to
/// make: a token and a desk identity both need entropy, which `prism-core` is
/// not allowed to have (it is platform-neutral and dependency-free by rule) and
/// which a **client** must not supply — a client that chose a token would be
/// choosing this desk's password, and one that chose a CID would be able to give
/// two desks the same one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[cfg_attr(any(test, feature = "proptest"), derive(proptest_derive::Arbitrary))]
#[serde(tag = "t", rename_all_fields = "camelCase")]
pub enum MachineChange {
    /// Whether the named pipe / Unix domain socket is opened at all.
    Local {
        /// Open it.
        local: bool,
    },
    /// Where the WebSocket listener binds, or `None` for not at all.
    ///
    /// An address that is **not** loopback is refused unless a token is set
    /// (`docs/IPC_PROTOCOL.md` §2.1). That refusal is the whole of the network
    /// exposure rule, and it is here rather than in an interface so that a
    /// second client cannot enable LAN access without one.
    Websocket {
        /// The address, or `None`.
        ///
        /// `crate::socket::option` because `rmp-serde` is not symmetric about
        /// `SocketAddr` — S33's finding, and `wire.rs`'s round-trip property
        /// found it again here within a minute of this variant existing.
        #[serde(with = "crate::socket::option")]
        #[cfg_attr(
            any(test, feature = "proptest"),
            proptest(strategy = "crate::arb::maybe_socket()")
        )]
        #[ts(type = "string | null")]
        address: Option<SocketAddr>,
    },
    /// The §2.1 token, written by an operator who has one already.
    ///
    /// Blank is `None`, for `MachineConfig::set_surface_port`'s reason: a
    /// cleared box means *no token* and a stored `""` would be a token that
    /// nothing can ever match and that would still count as one.
    Token {
        /// The token, or `None` for none at all.
        token: Option<String>,
    },
    /// Make a token. The daemon generates it and the interface displays it —
    /// §2.1 in as many words.
    NewToken,
    /// How much to log.
    LogLevel {
        /// The new level.
        level: LogLevel,
    },
    /// How many universes the frame layout carries, `1..=64`.
    Universes {
        /// The new count.
        universes: u32,
    },
    /// What the stage does when the daemon stops.
    ExitAction {
        /// Hold or blackout.
        action: ExitAction,
    },
    /// Whether the desk starts with the machine — `ARCHITECTURE_SPEC.md` §10.3
    /// and S29.
    Autostart {
        /// Start at login.
        autostart: bool,
    },
    /// Where the installed fixture library is, or `None` to look beside the
    /// executable.
    FixtureLibrary {
        /// The directory.
        path: Option<String>,
    },
    /// Which X-Touch binding profile is in force, or `None` for the built-in
    /// table.
    ///
    /// **Setting it re-reads the file**, which is what makes this the *reload*
    /// the Devices panel needs: a profile edited beside the daemon is picked up
    /// by naming it again. A profile that is missing or malformed is reported
    /// and the built-in bindings stand, which is S22's rule and is why this
    /// never refuses.
    SurfaceProfile {
        /// The path.
        path: Option<String>,
    },
    /// Give this desk a new identity, because it is sharing one.
    ///
    /// See the module documentation for why it waits for a restart.
    NewIdentity,
}

impl MachineChange {
    /// Whether this change is one the daemon can only make on the way up.
    ///
    /// The same question [`crate::OutputInstance::needs_restart`] answers for a
    /// rig, and the same reason for asking it in the domain: an interface that
    /// kept its own list of which rows are live would be a second answer, and
    /// the one that is wrong is the one an operator believes.
    ///
    /// A listener is bound once and a frame layout is built once. The identity
    /// is here for a different reason and it is the interesting one — see the
    /// module documentation.
    #[must_use]
    pub const fn needs_restart(&self) -> bool {
        matches!(
            self,
            Self::Local { .. }
                | Self::Websocket { .. }
                | Self::Token { .. }
                | Self::NewToken
                | Self::Universes { .. }
                | Self::FixtureLibrary { .. }
                | Self::NewIdentity
        )
    }
}

/// A setting this run's command line is holding, so the stored one is neither
/// read nor written.
///
/// S33's rule for `--mock-output` and S36's for `--surface`, generalised: a flag
/// is *the value for the run*. An interface draws the row, shows what is in
/// force and says which flag is holding it, rather than offering a box that
/// would appear to work and vanish at the next restart.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, TS)]
#[cfg_attr(any(test, feature = "proptest"), derive(proptest_derive::Arbitrary))]
pub enum MachineOverride {
    /// `--mock-output` and its four companions: the rig is this run's.
    Outputs,
    /// `--surface`: the control surface's port is this run's.
    Surface,
    /// `--no-local`.
    Local,
    /// `--websocket`.
    Websocket,
    /// `--token`.
    Token,
    /// `--log-level`.
    LogLevel,
    /// `--universes`.
    Universes,
    /// `--blackout-on-exit` or `--hold-on-exit`.
    ExitAction,
    /// `--fixtures`.
    FixtureLibrary,
    /// `--surface-profile`.
    SurfaceProfile,
}

impl MachineOverride {
    /// The flag an operator would have typed, for a panel that has to name it.
    #[must_use]
    pub const fn flag(self) -> &'static str {
        match self {
            Self::Outputs => "--mock-output",
            Self::Surface => "--surface",
            Self::Local => "--no-local",
            Self::Websocket => "--websocket",
            Self::Token => "--token",
            Self::LogLevel => "--log-level",
            Self::Universes => "--universes",
            Self::ExitAction => "--blackout-on-exit",
            Self::FixtureLibrary => "--fixtures",
            Self::SurfaceProfile => "--surface-profile",
        }
    }
}

/// Everything the *This machine* panel draws — S37.
///
/// Carried whole in the `Snapshot` and whole again in
/// [`crate::Delta::MachineChanged`], for [`crate::Delta::OutputsChanged`]'s
/// reason: it is a handful of fields rather than a document, and a client that
/// had to diff a JSON patch to redraw a settings panel would be doing arithmetic
/// to learn something it can be told.
///
/// Some of it is **not** configuration. The data directory, the endpoints that
/// are actually listening and the overrides are facts about the run, and they
/// are here rather than in a query because they change when a command changes
/// them and at no other time — which is the same test `Delta::SurfaceChanged`
/// passes and `Query::MidiPorts` fails.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS)]
#[cfg_attr(any(test, feature = "proptest"), derive(proptest_derive::Arbitrary))]
#[serde(rename_all = "camelCase")]
pub struct MachineSettings {
    /// This desk's sACN CID, as canonical UUID text.
    pub desk_id: String,
    /// Where the lock file, the machine configuration and the default show
    /// live.
    ///
    /// **Read, never written.** The settings themselves are in this directory,
    /// so a daemon told to move it would have to be told somewhere else — see
    /// `ARCHITECTURE_SPEC.md` §10.3.
    pub data_dir: String,
    /// Whether the local pipe / Unix domain socket is configured open.
    pub local: bool,
    /// Where the WebSocket listener is configured, or `None`.
    #[serde(with = "crate::socket::option")]
    #[cfg_attr(
        any(test, feature = "proptest"),
        proptest(strategy = "crate::arb::maybe_socket()")
    )]
    #[ts(type = "string | null")]
    pub websocket: Option<SocketAddr>,
    /// Where it is **actually** listening, which is `None` when the address is
    /// taken by something else.
    ///
    /// Configured and absent at the same time is an ordinary state and exactly
    /// the one a panel has to draw — S36's `configured` and `open` for a MIDI
    /// port, one device along.
    #[serde(with = "crate::socket::option")]
    #[cfg_attr(
        any(test, feature = "proptest"),
        proptest(strategy = "crate::arb::maybe_socket()")
    )]
    #[ts(type = "string | null")]
    pub websocket_open: Option<SocketAddr>,
    /// The §2.1 token, or `None`.
    ///
    /// **Shown rather than hidden**, because §2.1 says the daemon generates it
    /// and the interface displays it: an operator who cannot read it cannot type
    /// it into the phone in the auditorium, and a token nobody can read is a
    /// network exposure nobody can use.
    pub token: Option<String>,
    /// How much the daemon logs.
    pub log_level: LogLevel,
    /// How many universes the frame layout carries.
    pub universes: u32,
    /// What the stage does when the daemon stops.
    pub exit_action: ExitAction,
    /// Whether the desk starts with the machine (S29).
    pub autostart: bool,
    /// Where the installed fixture library is, or `None`.
    pub fixture_library: Option<String>,
    /// Which binding profile is in force, or `None` for the built-in table.
    pub surface_profile: Option<String>,
    /// Which settings this run's command line is holding.
    #[cfg_attr(
        any(test, feature = "proptest"),
        proptest(strategy = "crate::arb::small_vec(3)")
    )]
    pub overrides: Vec<MachineOverride>,
}

impl MachineSettings {
    /// Whether the command line is holding `setting` this run.
    #[must_use]
    pub fn is_overridden(&self, setting: MachineOverride) -> bool {
        self.overrides.contains(&setting)
    }
}

/// What the *Show files* panel reads — S37.
///
/// The show a daemon has open is state the daemon owns and that only a command
/// changes, so it travels as [`crate::Delta::ShowFileChanged`] and rides in the
/// `Snapshot`, rather than being asked for.
///
/// **There is no age in it, deliberately.** S33's rule is that a status a client
/// reads carries an age rather than a time, because the daemon and a browser
/// have no shared clock; the rule one step further along is that a field which
/// would have to carry an age is a field a delta cannot carry at all, since the
/// age is stale the moment it is sent. What the autosave is really being asked
/// is *is there a recovery copy sitting beside my show*, and that is a fact
/// rather than a moment.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS)]
#[cfg_attr(any(test, feature = "proptest"), derive(proptest_derive::Arbitrary))]
#[serde(rename_all = "camelCase")]
pub struct ShowFileInfo {
    /// The `.prism` file this daemon has open.
    pub path: String,
    /// Shows opened before it, most recent first, without this one.
    #[cfg_attr(
        any(test, feature = "proptest"),
        proptest(strategy = "crate::arb::small_vec(3)")
    )]
    pub recent: Vec<String>,
    /// Whether there are edits that are not in the file — the Save lamp.
    pub unsaved_changes: bool,
    /// Whether a recovery copy is standing beside the show.
    ///
    /// One is written every [`Self::autosave_seconds`] while there are unsaved
    /// changes, and removed by a save. So *yes* means the daemon has a copy of
    /// work that is not in the operator's own file, which is the one thing a
    /// panel has to be able to say about an autosave.
    pub recovery: bool,
    /// How often the recovery copy is written.
    pub autosave_seconds: u32,
}

#[cfg(test)]
mod tests {
    use super::{ExitAction, LogLevel, MachineChange, MachineOverride, MachineSettings};

    #[test]
    fn a_setting_that_is_bound_once_needs_a_restart_and_the_rest_do_not() {
        // The live ones. A log level is a switch, an exit action is read when
        // the daemon stops, an autostart flag is read by the shell, and a
        // binding profile is re-read on the spot — which is what makes naming
        // it again the *reload* the Devices panel needs.
        for change in [
            MachineChange::LogLevel {
                level: LogLevel::Debug,
            },
            MachineChange::ExitAction {
                action: ExitAction::Blackout,
            },
            MachineChange::Autostart { autostart: true },
            MachineChange::SurfaceProfile { path: None },
        ] {
            assert!(!change.needs_restart(), "{change:?}");
        }

        // And the ones a running daemon cannot take back: a listener is bound
        // once, a frame layout is built once, and an sACN source that changed
        // its CID mid-show would fight the source it used to be.
        for change in [
            MachineChange::Local { local: false },
            MachineChange::Websocket { address: None },
            MachineChange::Token { token: None },
            MachineChange::NewToken,
            MachineChange::Universes { universes: 4 },
            MachineChange::FixtureLibrary { path: None },
            MachineChange::NewIdentity,
        ] {
            assert!(change.needs_restart(), "{change:?}");
        }
    }

    #[test]
    fn an_override_names_the_flag_that_is_holding_it() {
        assert_eq!(MachineOverride::Outputs.flag(), "--mock-output");
        assert_eq!(MachineOverride::Surface.flag(), "--surface");
        assert_eq!(MachineOverride::Local.flag(), "--no-local");
        assert_eq!(MachineOverride::Websocket.flag(), "--websocket");
        assert_eq!(MachineOverride::Token.flag(), "--token");
        assert_eq!(MachineOverride::LogLevel.flag(), "--log-level");
        assert_eq!(MachineOverride::Universes.flag(), "--universes");
        assert_eq!(MachineOverride::ExitAction.flag(), "--blackout-on-exit");
        assert_eq!(MachineOverride::FixtureLibrary.flag(), "--fixtures");
        assert_eq!(MachineOverride::SurfaceProfile.flag(), "--surface-profile");
    }

    #[test]
    fn the_settings_say_which_rows_a_command_line_is_holding() {
        let settings = MachineSettings {
            overrides: vec![MachineOverride::Outputs, MachineOverride::Universes],
            ..MachineSettings::default()
        };
        assert!(settings.is_overridden(MachineOverride::Universes));
        assert!(!settings.is_overridden(MachineOverride::Websocket));
    }

    /// The defaults are what a desk that has never been configured runs as, so
    /// they are asserted rather than assumed: `Info`, hold the stage, and no
    /// autostart.
    #[test]
    fn the_defaults_are_a_quiet_desk_that_holds_its_stage() {
        assert_eq!(LogLevel::default(), LogLevel::Info);
        assert_eq!(ExitAction::default(), ExitAction::Hold);
        let settings = MachineSettings::default();
        assert!(!settings.autostart);
        assert_eq!(settings.token, None);
    }
}
