//! Round-trip property tests for every domain type.
//!
//! S1 exit criterion: *every type survives serialise → deserialise unchanged*.
//! Both codecs are checked, because both are real:
//!
//! - **JSON** — show export/import (`IMPLEMENTATION_PLAN.md` S15) and every
//!   human-readable dump.
//! - **MessagePack** — the IPC wire (`docs/IPC_PROTOCOL.md` §3). It is encoded
//!   with `to_vec_named`, because the compact array encoding cannot carry the
//!   `t` tag of an internally tagged enum.
//!
//! The last test in this module closes the loop: it asserts that every type with
//! a generated TypeScript binding also appears in the list below, so a new type
//! cannot be added and quietly skip its round-trip.

use proptest::prelude::*;

/// One round-trip property per type, plus the list of covered type names.
///
/// The strategy is `.boxed()`, which looks like noise and is not. `Command` is
/// a large enum and `proptest_derive` builds **one value tree holding every
/// variant's tree at once**; the thirty-sixth variant tipped `prism-core`'s
/// `tests/oops.rs` and `prism-ipc`'s `tests/framing.rs` into a stack overflow in
/// a debug build (S34's finding), and S40's seven — two of which carry two
/// `ObjectRef`s apiece — tipped this one. Boxing puts that tree on the heap.
/// **A session adding a command should reach for this and not for
/// `RUST_MIN_STACK`**, which only moves the cliff.
macro_rules! round_trip {
    ($($name:ident => $ty:ty),* $(,)?) => {
        /// Every type covered by a round-trip property, by TypeScript name.
        ///
        /// `Command` is in the list without being in the macro: its round trip
        /// is written out below, because it is generated by
        /// `crate::arb::command` rather than by its own derive — see the budget
        /// test at the end of this module.
        const COVERED: &[&str] = &["crate::Command", $(stringify!($ty)),*];

        $(
            proptest! {
                #![proptest_config(ProptestConfig::with_cases(64))]

                #[test]
                fn $name(value in any::<$ty>().boxed()) {
                    let json = serde_json::to_string(&value)
                        .expect("every domain type must serialise to JSON");
                    let from_json: $ty = serde_json::from_str(&json)
                        .expect("JSON produced by this type must deserialise");
                    prop_assert_eq!(&value, &from_json, "JSON round trip changed the value");

                    let packed = rmp_serde::to_vec_named(&value)
                        .expect("every domain type must serialise to MessagePack");
                    let from_msgpack: $ty = rmp_serde::from_slice(&packed)
                        .expect("MessagePack produced by this type must deserialise");
                    prop_assert_eq!(&value, &from_msgpack, "MessagePack round trip changed the value");
                }
            }
        )*
    };
}

round_trip! {
    fixture_id => crate::FixtureId,
    group_id => crate::GroupId,
    sequence_id => crate::SequenceId,
    executor_id => crate::ExecutorId,
    preset_id => crate::PresetId,
    universe_id => crate::UniverseId,
    session_id => crate::SessionId,
    view_id => crate::ViewId,
    window_instance_id => crate::WindowInstanceId,
    output_id => crate::OutputId,

    attribute_type => crate::AttributeType,
    feature_group => crate::FeatureGroup,
    merge_mode => crate::MergeMode,
    attribute_def => crate::AttributeDef,
    fixture_type => crate::FixtureType,

    vec3 => crate::Vec3,
    rgb_color => crate::RgbColor,
    fixture => crate::Fixture,
    group => crate::Group,

    preset_value => crate::PresetValue,
    preset_pool => crate::PresetPool,
    preset => crate::Preset,

    cue_trigger => crate::CueTrigger,
    cue_property => crate::CueProperty,
    cue_part => crate::CuePart,
    cue => crate::Cue,
    cue_edit => crate::CueEdit,
    sequence => crate::Sequence,
    sequence_store_mode => crate::SequenceStoreMode,

    executor_button_function => crate::ExecutorButtonFunction,
    executor_button_ref => crate::ExecutorButtonRef,
    executor_fader_function => crate::ExecutorFaderFunction,
    executor_encoder_function => crate::ExecutorEncoderFunction,
    executor => crate::Executor,

    programmer_value_source => crate::ProgrammerValueSource,
    clear_stage => crate::ClearStage,
    programmer_value => crate::ProgrammerValue,
    programmer_entry => crate::ProgrammerEntry,
    programmer_state => crate::ProgrammerState,

    window_type => crate::WindowType,
    window_instance => crate::WindowInstance,
    view => crate::View,
    session => crate::Session,

    json_value => crate::JsonValue,
    json_patch_op => crate::JsonPatchOp,
    output_health => crate::OutputHealth,
    art_net_port => crate::ArtNetPort,
    sacn_port => crate::SacnPort,
    output_kind => crate::OutputKind,
    output_instance => crate::OutputInstance,
    output_change => crate::OutputChange,
    notice_level => crate::NoticeLevel,
    midi_port_info => crate::MidiPortInfo,
    surface_health => crate::SurfaceHealth,
    surface_status => crate::SurfaceStatus,
    output_status_info => crate::OutputStatusInfo,
    log_level => crate::LogLevel,
    exit_action => crate::ExitAction,
    machine_change => crate::MachineChange,
    machine_override => crate::MachineOverride,
    machine_settings => crate::MachineSettings,
    show_file_info => crate::ShowFileInfo,

    strip_button => crate::StripButton,
    global_button => crate::GlobalButton,
    bound_control => crate::BoundControl,
    executor_target => crate::ExecutorTarget,
    step => crate::Step,
    surface_action => crate::SurfaceAction,
    surface_binding => crate::SurfaceBinding,
    surface_control => crate::SurfaceControl,

    playback_id => crate::PlaybackId,
    playback_target => crate::PlaybackTarget,
    object_ref => crate::ObjectRef,
    overwrite_mode => crate::OverwriteMode,

    selection_mode => crate::SelectionMode,
    go_direction => crate::GoDirection,
    param_direction => crate::ParamDirection,
    delta => crate::Delta,

    library_entry => crate::LibraryEntry,
    patch_conflict => crate::PatchConflict,
    patch_preview => crate::PatchPreview,
    store_target => crate::StoreTarget,
    store_mode => crate::StoreMode,
    store_preview => crate::StorePreview,
    query => crate::Query,
    answer => crate::Answer,
}

/// Pins the reason [`crate::arb::finite_f64`] generates bounded-precision
/// values.
///
/// `serde_json` writes the shortest text that identifies an `f64` — the standard
/// library reads that text back exactly — but `serde_json`'s own parser is not
/// correctly rounded and returns a neighbouring value. MessagePack, being binary
/// IEEE 754, is exact.
///
/// This matters beyond the tests: the show export in S15 is JSON, so a saved and
/// reloaded show must not be assumed bit-identical in its floats unless values
/// are written at a bounded precision.
#[test]
fn json_floats_are_only_exact_to_bounded_precision() {
    let full_precision = -971_744.715_983_591_5_f64;
    let text = serde_json::to_string(&full_precision).unwrap();
    assert_eq!(text.parse::<f64>().unwrap(), full_precision);
    assert_ne!(
        serde_json::from_str::<f64>(&text).unwrap(),
        full_precision,
        "serde_json's float parser has become exact - the bounded-precision \
         strategies in `arb` can be widened"
    );

    let bounded = -971_744.716_f64;
    assert_eq!(
        serde_json::from_str::<f64>(&serde_json::to_string(&bounded).unwrap()).unwrap(),
        bounded
    );
}

/// The TypeScript name of a covered type, i.e. `Command` from `crate :: Command`
/// as `stringify!` renders it.
fn short_name(path: &str) -> &str {
    path.rsplit(':').next().unwrap_or(path).trim()
}

#[test]
fn every_exported_type_has_a_round_trip_property() {
    let covered: Vec<&str> = COVERED.iter().copied().map(short_name).collect();
    let missing: Vec<&String> = crate::export::exported_once()
        .iter()
        .filter(|name| !covered.contains(&name.as_str()))
        .collect();
    assert!(
        missing.is_empty(),
        "these types have TypeScript bindings but no round-trip property: {missing:?}"
    );
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    /// `Command`'s round trip, written out because its strategy is not its
    /// derive.
    ///
    /// Everything else in this module goes through `round_trip!` with
    /// `any::<T>()`. `Command` is generated by `crate::arb::command`, which is
    /// the same vocabulary in six boxed groups — see the budget test below for
    /// the measurement that made that necessary. The property itself is
    /// identical to the macro's, and it is spelled out rather than special-cased
    /// inside the macro so the macro stays one rule.
    #[test]
    fn command(value in crate::arb::command()) {
        let json = serde_json::to_string(&value)
            .expect("every domain type must serialise to JSON");
        let from_json: crate::Command = serde_json::from_str(&json)
            .expect("JSON produced by this type must deserialise");
        prop_assert_eq!(&value, &from_json, "JSON round trip changed the value");

        let packed = rmp_serde::to_vec_named(&value)
            .expect("every domain type must serialise to MessagePack");
        let from_msgpack: crate::Command = rmp_serde::from_slice(&packed)
            .expect("MessagePack produced by this type must deserialise");
        prop_assert_eq!(&value, &from_msgpack, "MessagePack round trip changed the value");
    }
}

/// How much stack one generated `Command` costs, as a budget rather than a
/// story.
///
/// # Why this is a test and not a comment
///
/// Three sessions have now been surprised by the same thing: `proptest_derive`
/// builds one **value tree** per generated value holding a slot for every
/// variant, that tree is constructed as a local before it is moved into a
/// `Box`, and a debug test thread on Windows has 2 MiB. The symptom is a
/// `STATUS_STACK_OVERFLOW` in a *different crate's* test target with no failing
/// case to read — S34 met it at the thirty-sixth variant, S40 at the
/// forty-second, and S37 at the fifty-fourth, in `prism-core`'s `tests/oops.rs`
/// both of the last two times.
///
/// The remedy has always been the same and is `crate::arb::boxed`: boxing a
/// **field's** strategy replaces its whole subtree with a pointer. What was
/// missing was a way to find out before CI did, so here it is. The two numbers
/// in the budget are measured rather than guessed: with `Copy`, `Move`,
/// `ExecutorGo`, `SetSurfacePort` and the five `Option<SequenceId>` fields
/// unboxed the tree was **36 160 bytes** and `oops.rs` overflowed; with them
/// boxed it is **30 992** and it does not.
///
/// **A session that fails this boxes a field.** `RUST_MIN_STACK` only moves the
/// cliff a few variants along, and it moves it in one crate rather than in the
/// four that generate commands.
///
/// # What S38 measured, and why `Command` was the wrong thing to watch
///
/// The cost is **560 bytes per variant, whatever the variant carries**: two bare
/// unit variants added to `Command` took its tree from 32 144 to 33 264. So the
/// tree grows with the *number* of alternatives and not with their payloads, and
/// four sessions' remedy — box the fat field — buys nothing once every fat field
/// is a pointer.
///
/// Two things follow, and the second is the one that bit.
///
/// **A new command is expensive and a new `MachineChange` is free.** S38 wanted
/// to say two new things about the desk and put both in [`crate::MachineChange`],
/// which travels boxed inside `Command::ConfigureMachine`: `Command`'s tree is
/// unchanged at 30 992, and the protocol is better for it — what a desk's keys do
/// is one of this machine's settings, beside the profile file they used to be
/// read from.
///
/// **A wide unit enum is the expensive thing, and it is invisible from here.**
/// `GlobalButton` is sixty-four buttons carrying nothing, and its derived tree
/// was **36 064 bytes** — larger than the whole of `Command`. Everything holding
/// one inherited it (`BoundControl` 41 200, `MachineChange` 81 440), and
/// `prism-core`'s `tests/command_application.rs` and `tests/oops.rs` both
/// overflowed a debug test thread with this test green and `Command` unmoved at
/// 30 992. `crate::arb::boxed` cannot reach that: boxing a field replaces the
/// subtree with a pointer but the subtree is still *built* as a local before the
/// box takes it, so a 36 KB tree behind a pointer is a 36 KB frame at generation
/// time.
///
/// What reaches it is **not having the tree**:
/// `crate::arb::arbitrary_from_list` maps a range onto the enum's own `ALL`, and
/// it is applied to every unit enum wide enough to matter. Measured, before and
/// after: `GlobalButton` 36 064 → 16, `AttributeType` 8 464 → 16, `WindowType`
/// 6 224 → 16, `ExecutorButtonFunction` 4 512 → 16, `FeatureGroup` 2 832 → 16,
/// and with them `BoundControl` 41 200 → 3 392 and `ExecutorButtonRef`
/// 5 120 → 1 152. **A session adding a unit enum with more than a handful of
/// variants should reach for that macro**, and one adding a payload should still
/// reach for `boxed`.
///
/// # The budget is the measured figure since S38, not a round number above it
///
/// S37 set it at 32 KiB, which sat **above** the largest tree that had ever been
/// shown to be safe: the two numbers it measured were 36 160 (overflows) and
/// 30 992 (does not), and 32 768 is in the gap between them where nothing had
/// been tried. S38 landed in that gap — a `Command` tree of **32 144** bytes,
/// this test green, and `prism-core`'s suite overflowing exactly as before. A
/// budget above the demonstrated ceiling is a budget that reports a pass for a
/// build that does not run. S43 met 32 144 again, from two added commands, and
/// `tests/oops.rs` died with `STATUS_STACK_OVERFLOW` exactly as recorded — so
/// the ceiling is a real measurement rather than a story about an old toolchain.
///
/// # And `Command` is measured through `crate::arb::command` since S43
///
/// The remedy in the section above stopped working, and it is worth being
/// precise about why. S43 boxed a field of the offending variant and the total
/// **did not move by one byte**: a `TupleUnion` slot costs about 576 bytes
/// whatever the variant carries, so what was being paid for was never the
/// payload — it was the *count*. At fifty-five variants `Command` was 30 992,
/// which is the whole of the budget; the protocol had no room left to grow at
/// all, and no amount of boxing could make any.
///
/// So `Command` is generated by [`crate::arb::command`], which is the same
/// vocabulary in six boxed groups: one slot per group rather than per variant,
/// and only the chosen group is ever built. `Command`'s own derive is kept and
/// is what [`crate::arb`]'s coverage test compares against, but nothing
/// generates values from it — measuring it here would measure a tree nothing
/// builds.
///
/// **A session that fails this now has found something new**, because a group
/// costs what a variant used to and there are six of them.
#[test]
fn a_generated_wire_value_fits_in_a_test_thread() {
    // Measured rather than rounded — see above. 36 160 and 32 144 both overflow
    // `prism-core`'s suite; 30 992 is what the whole suite runs on.
    const BUDGET: usize = 30_992;
    let sizes = [
        (
            "Command",
            size_of::<<crate::arb::BoxedCommand as Strategy>::Tree>(),
        ),
        (
            "Delta",
            size_of::<<<crate::Delta as Arbitrary>::Strategy as Strategy>::Tree>(),
        ),
        (
            "Query",
            size_of::<<<crate::Query as Arbitrary>::Strategy as Strategy>::Tree>(),
        ),
        (
            "Answer",
            size_of::<<<crate::Answer as Arbitrary>::Strategy as Strategy>::Tree>(),
        ),
    ];
    for (name, size) in sizes {
        assert!(
            size <= BUDGET,
            "a {name} value tree is {size} bytes, over the {BUDGET}-byte budget: \n             split the strategy into more boxed groups (crate::arb::command), or \n             make a wide unit enum cheap with crate::arb::arbitrary_from_list"
        );
    }
}
